apiVersion: v1
kind: Pod
metadata:
  name: spark-cpu
  labels:
    k8s-app: spark-cpu
spec:
  containers:
  - name: spark-cpu
    image: sdsc/words-caffe-py3:latest
    # image: gitlab-registry.nautilus.optiputer.net/greencodes/images/master/cpu-jupyter-dask:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: "4G"
        #cpu: 32
      requests:
        memory: "2G"
        #cpu: 8
    volumeMounts:
      - name: nfs
        mountPath: "/nfs"
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs-pvc
  restartPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: spark-cpu
  name: spark-cpu
spec:
  type: NodePort
  ports:
  - port: 8888
    name: web
  - port: 8787
    name: dask-main
  - port: 8788
    name: dask-debug
  selector:
    k8s-app: spark-cpu
